name: ytown_listings
version: "0.1.0"
profile: ytown_listings

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  ytown_listings:
    +database: lake
    +materialized: table
    raw:
      +schema: raw
    staging:
      +schema: stg
    marts:
      +schema: marts

snapshots:
  ytown_listings:
    +database: lake
    +schema: marts
