name: ytown_listings
version: "0.1.0"
profile: ytown_listings

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

vars:
  bi_export_dir: ../evidence/sources/lake

models:
  ytown_listings:
    +database: lake
    +materialized: table
    raw:
      +schema: raw
    staging:
      +schema: stg
    marts:
      +schema: marts
      +post-hook: "{{ export_to_parquet(var('bi_export_dir')) }}"

snapshots:
  ytown_listings:
    +database: lake
    +schema: marts
    +post-hook: "{{ export_to_parquet(var('bi_export_dir')) }}"
